// data.js
const vegetableData = [
    { no: "01", name: "බෝංචි", tags: ["bonchi", "beans", "බෝංචි"] },
    { no: "02", name: "ලීක්ස්", tags: ["leeks", "ලීක්ස්", "leks", "liks", "liiks"] },
    { no: "03", name: "කැරට්", tags: ["carrot", "කැරට්", "karrot", "karot", "carot"] },
    { no: "04", name: "කොළ බීට්", tags: ["kola beet", "beetroot leaves", "කොළ බීට්"] },
    { no: "05", name: "කහ බීට්", tags: ["kaha beet", "yellow beet", "කහ බීට්"] },
    { no: "06", name: "ගෝවා", tags: ["gowa", "gova", "goova", "cabbage", "ගෝවා"] },
    { no: "07", name: "මාළු මිරිස්", tags: ["malu miris", "capsicum", "මාළු මිරිස්"] },
    { no: "08", name: "තක්කාලි", tags: ["thakkali", "tomato", "takkali", "තක්කාලි"] },
    { no: "09", name: "තිලිණි තක්කාලි", tags: ["thilini thakkali", "තිලිනි තක්කාලි","තිලිණි තක්කාලි"] },
    { no: "10", name: "අමුමිරිස්", tags: ["amu miris", "green chili", "අමුමිරිස්", "amumiris"] },
    { no: "11", name: "දෙහි", tags: ["dehi", "lime", "දෙහි", "dihi", "dhehi", "dhihi", "dhehe"] },
    { no: "12", name: "නොකෝල්", tags: ["nokol", "knolkhol", "නොකෝල්"] },
    { no: "13", name: "රාබු", tags: ["rabu", "radish", "raabu", "රාබු"] },
    { no: "14", name: "අතු ගෝවා", tags: ["athu gowa", "athu gova", "athu goova", "අතු ගෝවා"] },
    { no: "15", name: "ලංකා අල", tags: ["lanka ala", "ලංකා අල"] },
    { no: "16", name: "අල", tags: ["ala", "potato", "අල"] },
    { no: "17", name: "බී ලූණු", tags: ["b lunu", "onion", "බී ලූණු"] },
    { no: "18", name: "රතු ලූණු", tags: ["rathu lunu", "red onion", "රතු ලූණු"] },
    { no: "19", name: "සුදු ලූණු", tags: ["sudu lunu", "garlic", "සුදු ලූණු"] },
    { no: "20", name: "බටු", tags: ["batu", "eggplant", "brinjal", "බටු"] },
    { no: "21", name: "එළ බටු", tags: ["ela batu", "එළ බටු"] },
    { no: "22", name: "තිත් බටු", tags: ["thith batu", "තිත් බටු"] },
    { no: "23", name: "කරවිල", tags: ["karavila", "bitter gourd", "කරවිල"] },
    { no: "24", name: "මෑකරල්", tags: ["mackerel", "beans", "මෑකරල්"] },
    { no: "25", name: "වැටකොළු", tags: ["watakolu", "ridged gourd", "වැටකොළු"] },
    { no: "26", name: "පතෝල", tags: ["pathola", "snake gourd", "පතෝල", "patola"] },
    { no: "27", name: "බණ්ඩක්කා", tags: ["bandakka", "okra", "ladyfingers", "බණ්ඩක්කා"] },
    { no: "28", name: "කැකිරි", tags: ["kekiri", "cucumber", "කැකිරි"] },
    { no: "29", name: "පිපිඤ්ඤා", tags: ["pipinna", "cucumber", "පිපිඤ්ඤා"] },
    { no: "30", name: "අළු කෙසෙල්", tags: ["alu kesel", "plantain", "අළු කෙසෙල්"] },
    { no: "31", name: "මුරුංගා", tags: ["murunga", "drumstick", "මුරුංගා"] },
    { no: "32", name: "දඹල", tags: ["dambala", "winged bean", "දඹල", "dabala", "dhabala"] },
    { no: "33", name: "ළූණු කොළ​", tags: ["lunu kola", "luunu kola", "lonu kola", "ළූණු කොළ​ කොළ"] },
    { no: "34", name: "ඉන් අල", tags: ["in ala", "ඉන් අල"] },
    { no: "35", name: "බතල", tags: ["bathala", "sweet potato", "බතල"] },
    { no: "36", name: "කෙසෙල් මුව", tags: ["kesel muwa", "banana flower", "කෙසෙල් මුව"] },
    { no: "37", name: "කොහිල", tags: ["kohila", "කොහිල"] },
    { no: "38", name: "බටර් බෝංචි", tags: ["butter bonchi", "butter beans", "බටර් බෝංචි"] },
    { no: "39", name: "ගස් බෝංචි", tags: ["gas bonchi", "ගස් බෝංචි"] },
    { no: "40", name: "මැලේ වට්ටක්කා", tags: ["male wattakka", "mele wattakka", "vattakka", "මැලේ වට්ටක්කා", "මලේ වට්ටක්කා"] },
    { no: "41", name: "මිමිනි වට්ටක්කා", tags: ["mimini wattakka", "vattakka", "මිමිනි වට්ටක්කා", "මිමිණි වට්ටක්කා"] },
    { no: "42", name: "ලංකා වට්ටක්කා", tags: ["lanka wattakka", "pumpkin", "vattakka", "ලංකා වට්ටක්කා"] },
    { no: "43", name: "බටානා", tags: ["batana", "බටානා"] },
    { no: "44", name: "බිම්මල්", tags: ["bimmals", "mushrooms", "බිම්මල්"] },
    { no: "45", name: "අඹරැල්ලා", tags: ["ambaralla", "eberella", "අඹරැල්ලා", "embarella", "ebarella", "embarella", "emberella", "hog plum"] },
    { no: "46", name: "පැපොල්", tags: ["papol", "papaya", "පැපොල්"] },
    { no: "47", name: "පැණි කොමඩු", tags: ["pani komadu", "watermelon", "පැණි කොමඩු"] },
    { no: "48", name: "සීනි කෙසෙල්", tags: ["seeni kesel", "sini kesel", "banana", "සීනි කෙසෙල්", "සිනි කෙසෙල්"] },
    { no: "49", name: "ඇඹුල් කෙසෙල්", tags: ["ambul kesel", "ebul kesel", "abul kesel", "banana", "ඇඹුල් කෙසෙල්"] },
    { no: "50", name: "දෙල්", tags: ["del", "breadfruit", "දෙල්"] },
    { no: "51", name: "මඤ්ඤොක්කා", tags: ["manyokka", "mnyokka", "maiyokka", "mayokka", "mahyokka", "මඤ්ඤොක්කා"] },
    { no: "52", name: "නෙළුම් අල​", tags: ["nelum ala", "nalum ala", "නෙළුම් අල​"] },
    { no: "53", name: "කිරි අල", tags: ["kiri ala", "keri ala", "taro", "කිරි අල"] },
    { no: "54", name: "තුඹ කරවිල", tags: ["thumba karavila", "thuba karavila", "තුඹ කරවිල"] },
    { no: "55", name: "මල් ගෝවා", tags: ["mal gowa", "mal gova", "mal goova", "cauliflower", "මල් ගෝවා"] },
    { no: "56", name: "කරපිංචා", tags: ["karapincha", "curry leaves", "කරපිංචා"] },
    { no: "57", name: "මුකුණුවැන්න", tags: ["mukunuwanna", "මුකුණුවැන්න"] },
    { no: "58", name: "ගොටුකොළ", tags: ["gotukola", "ගොටුකොළ"] },
    { no: "59", name: "කංකුං", tags: ["kankun", "water spinach", "කංකුං"] },
    { no: "60", name: "කතුරු කොළ", tags: ["kathuru kola", "katuru kola", "කතුරු කොළ"] },
    { no: "61", name: "තම්පලා", tags: ["thampala", "amaranth", "තම්පලා", "tampala"] },
    { no: "62", name: "නිවිති", tags: ["nivithi", "spinach", "නිවිති", "niviti"] },
    { no: "63", name: "කොහිල දඬු", tags: ["kohila dadu", "කොහිල දඬු"] },
    { no: "64", name: "සලාද", tags: ["salada", "lettuce", "සලාද", "salata", "salatha"] },
    { no: "65", name: "මින්චි", tags: ["minchi", "mint", "මින්චි"] },
    { no: "66", name: "කොත්තමල්ලි", tags: ["koththamalli", "coriander", "කොත්තමල්ලි", "kottamalli"] }
];